/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Accounts.*;
import apexsystem.*;
import javax.swing.JFrame;

/**
 *
 * @author lpjan
 */
public class ClientForm extends JFrame {

    private User user;
    private ApexSystem system;
    private NotificationHandler notificationHandler;
    
    public ClientForm(User user, ApexSystem system) {
        this.user = user;
        this.system = system;
        this.notificationHandler = system.getNotificationHandler();
        initComponents();
        
        ShowNotifications();
        
        welcomeLabel.setText("Welcome " + user.getName());
        NotificationButton.setText("Notifications (" + notificationHandler.GetNotificationCount(user.getUserID()) + ")");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        ListResourcesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RequestResourceButton = new javax.swing.JButton();
        NotificationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 250));
        setMinimumSize(new java.awt.Dimension(500, 250));
        setPreferredSize(new java.awt.Dimension(750, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 300));

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel.setText("Apex Library");

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        welcomeLabel.setText("Welcome ##Name##");

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        ListResourcesButton.setText("List Resources");
        ListResourcesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListResourcesButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Resources");

        RequestResourceButton.setText("Request a New Resource");
        RequestResourceButton.setActionCommand("");
        RequestResourceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestResourceButtonActionPerformed(evt);
            }
        });

        NotificationButton.setText("Notifications");
        NotificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NotificationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton))
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ListResourcesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RequestResourceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutButton)
                            .addComponent(NotificationButton)))
                    .addComponent(jLabel))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListResourcesButton)
                .addGap(18, 18, 18)
                .addComponent(RequestResourceButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        system.Logout();
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void ListResourcesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListResourcesButtonActionPerformed
        ResourceListForm rlForm = new ResourceListForm(system, user);
        
        rlForm.setVisible(true);
        rlForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_ListResourcesButtonActionPerformed

    private void NotificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificationButtonActionPerformed
        ShowNotifications();
    }//GEN-LAST:event_NotificationButtonActionPerformed

    private void RequestResourceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestResourceButtonActionPerformed
        NewPurchaseRequestForm form = new NewPurchaseRequestForm(system.getRequestHandler());
        
        form.setVisible(true);
        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_RequestResourceButtonActionPerformed
    
    private void ShowNotifications(){
        notificationHandler.ShowForUser(user.getUserID());
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListResourcesButton;
    private javax.swing.JButton NotificationButton;
    private javax.swing.JButton RequestResourceButton;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
