/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Resources.*;
import Accounts.*;
import apexsystem.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lpjan
 */
public class LoanRequestListForm extends javax.swing.JFrame {

    private ResourceHandler resourceHandler;
    private long lastClickTime;
    private User user;
    
    public LoanRequestListForm(ResourceHandler resourceHandler) {
        this.resourceHandler = resourceHandler;
        
        initComponents();
        
        FillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resourceTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        resourceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "User", "Days Requested"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resourceTable.setColumnSelectionAllowed(true);
        resourceTable.getTableHeader().setReorderingAllowed(false);
        resourceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resourceTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resourceTable);
        resourceTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (resourceTable.getColumnModel().getColumnCount() > 0) {
            resourceTable.getColumnModel().getColumn(0).setResizable(false);
            resourceTable.getColumnModel().getColumn(1).setResizable(false);
            resourceTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Double Click Item to review Loan Extension Request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resourceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resourceTableMouseClicked
        if (System.currentTimeMillis() - lastClickTime <= 500){
            System.out.println("Double Click");
            OpenItem();
        }
        
        lastClickTime = System.currentTimeMillis();
    }//GEN-LAST:event_resourceTableMouseClicked

    
    public void FillTable(){
        
        DefaultTableModel tableModel = (DefaultTableModel) resourceTable.getModel();
        tableModel.setRowCount(0);
              
        for (Resource resource : resourceHandler.resourceList) {
            if (resource.isExtensionRequested()) tableModel.addRow(new Object[]{resource.getName(), resource.getLoanedUser(), resource.getDaysRequested()});
        }
    }
    
    public void OpenItem(){
        for (Resource resource : resourceHandler.resourceList){
            if (resource.getName() == resourceTable.getValueAt(resourceTable.getSelectedRow(), 0) && resource.getLoanedUser() == resourceTable.getValueAt(resourceTable.getSelectedRow(), 1)){
                int input = JOptionPane.showConfirmDialog(this, "Do you want to grant this loan extension?", "Loan Extension", JOptionPane.YES_NO_OPTION);
            
                if (input == 0) {
                    resource.ExtendLoan();
                }
                else if (input == 1){
                    resource.DenyLoan();
                }
                
                FillTable();
                return;
            }
        }
        FillTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resourceTable;
    // End of variables declaration//GEN-END:variables
}