/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Accounts.User;
import Notifications.NotificationType;
import Resources.Resource;
import apexsystem.*;
import java.util.Date;

/**
 *
 * @author lpjan
 */
public class SendNewsletterForm extends javax.swing.JFrame {
    
    private ResourceHandler resourceHandler;
    private NotificationHandler notificationHandler;
    private LoginHandler loginHandler;
    
    /**
     * Creates new form SendNewsletterForm
     */
    public SendNewsletterForm(ApexSystem system) {
        this.resourceHandler = system.getResourceHandler();
        this.notificationHandler = system.getNotificationHandler();
        this.loginHandler = system.getLoginHandler();
        
        initComponents();
        
        DatePicker.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        resourceNumberLabel = new javax.swing.JLabel();
        SendNewsletterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Start Date:");

        DatePicker.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DatePickerPropertyChange(evt);
            }
        });

        jLabel2.setText("No. of Resources");

        resourceNumberLabel.setText("0");

        SendNewsletterButton.setText("Send Newsletter");
        SendNewsletterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendNewsletterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resourceNumberLabel)
                            .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(SendNewsletterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(resourceNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(SendNewsletterButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DatePickerPropertyChange
        Date pickedDate = DatePicker.getDate();
        int numberOfResources = 0;
        
        try{
            for (Resource resource : resourceHandler.resourceList){
                if (pickedDate.before(new Date(resource.getCreationDate()))){
                    numberOfResources++;
                }
            }
        }
        catch (NullPointerException e){
            System.out.println("Null Exception Caught");
        }
        
        resourceNumberLabel.setText(Integer.toString(numberOfResources));
    }//GEN-LAST:event_DatePickerPropertyChange

    private void SendNewsletterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendNewsletterButtonActionPerformed
        Date pickedDate = DatePicker.getDate();
        String text = "New Resources!";
        
        for (Resource resource : resourceHandler.resourceList){
            if (pickedDate.before(new Date(resource.getCreationDate()))){
                text += "\n" + resource.getName();
            }
        }
        
        for (User user : loginHandler.userList){
            notificationHandler.Add(user.getUserID(), "Resource Newsletter", text, NotificationType.INFO);
        }
        
        dispose();
    }//GEN-LAST:event_SendNewsletterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DatePicker;
    private javax.swing.JButton SendNewsletterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel resourceNumberLabel;
    // End of variables declaration//GEN-END:variables
}
